[package]
name = "_35__NumberGuessingGame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name = "_35__NumberGuessingGame"
path = "main.rs"
